"""
MongoDB models (Pydantic / Dict schemas) for THERMASHELL.
"""
from typing import List
import json
import uuid

def generate_uuid() -> str:
    return str(uuid.uuid4())

# Seed Data for Verified Materials
VERIFIED_MATERIALS_SEED: List[dict] = [
    {
        "id": "stone-masonry",
        "name": "Stone Masonry (Granite/Gneiss)",
        "category": "Masonry",
        "description": "High-density natural stone quarried in high-altitude Himalayan zones. Provides extreme thermal mass inertia.",
        "thermal_conductivity_k": 1.50,
        "density_rho": 2500.0,
        "specific_heat_cp": 900.0,
        "emissivity": 0.90,
        "solar_absorptivity": 0.65,
        "solar_reflectivity": 0.35,
        "embodied_carbon": 0.05,
        "cost": 1800.0,
        "units": "SI (W/mK, kg/m³, J/kgK)",
        "source": "IS 3792:1978 / NBC 2016",
        "reference": "Indian Standard Guide for Heat Insulation of Non-Industrial Buildings",
        "valid_temperature_range": "-50°C to 80°C",
    },
    {
        "id": "sandstone",
        "name": "Sandstone (Jaisalmer Arid)",
        "category": "Masonry",
        "description": "Yellow Jaisalmer sedimentary sandstone for hot-arid thermal damping and solar delay.",
        "thermal_conductivity_k": 1.70,
        "density_rho": 2200.0,
        "specific_heat_cp": 920.0,
        "emissivity": 0.88,
        "solar_absorptivity": 0.60,
        "solar_reflectivity": 0.40,
        "embodied_carbon": 0.06,
        "cost": 1400.0,
        "units": "SI (W/mK, kg/m³, J/kgK)",
        "source": "IS 3792:1978",
        "reference": "Guide for Heat Insulation of Buildings, Section 4",
        "valid_temperature_range": "-10°C to 90°C",
    },
    {
        "id": "burnt-clay-brick",
        "name": "Burnt Clay Brick Masonry",
        "category": "Masonry",
        "description": "Standard kiln-burnt clay brickwork in 1:6 cement mortar.",
        "thermal_conductivity_k": 0.84,
        "density_rho": 1800.0,
        "specific_heat_cp": 840.0,
        "emissivity": 0.90,
        "solar_absorptivity": 0.70,
        "solar_reflectivity": 0.30,
        "embodied_carbon": 0.24,
        "cost": 950.0,
        "units": "SI (W/mK, kg/m³, J/kgK)",
        "source": "IS 1077 / IS 3792",
        "reference": "Common Burnt Clay Building Bricks — Specification",
        "valid_temperature_range": "-30°C to 80°C",
    },
    {
        "id": "rammed-earth",
        "name": "Stabilized Rammed Earth / Mud",
        "category": "Masonry",
        "description": "Cement-stabilized compacted soil with high natural hygroscopic buffering.",
        "thermal_conductivity_k": 0.75,
        "density_rho": 1750.0,
        "specific_heat_cp": 880.0,
        "emissivity": 0.92,
        "solar_absorptivity": 0.68,
        "solar_reflectivity": 0.32,
        "embodied_carbon": 0.02,
        "cost": 450.0,
        "units": "SI (W/mK, kg/m³, J/kgK)",
        "source": "IS 2110:1980 / Auroville Earth Institute",
        "reference": "Code of practice for in-situ construction of walls in earth",
        "valid_temperature_range": "-20°C to 70°C",
    },
    {
        "id": "aac-block",
        "name": "Autoclaved Aerated Concrete (AAC)",
        "category": "Masonry",
        "description": "Micro-porous lightweight concrete block delivering combined structure and insulation.",
        "thermal_conductivity_k": 0.16,
        "density_rho": 550.0,
        "specific_heat_cp": 1000.0,
        "emissivity": 0.90,
        "solar_absorptivity": 0.50,
        "solar_reflectivity": 0.50,
        "embodied_carbon": 0.32,
        "cost": 1200.0,
        "units": "SI (W/mK, kg/m³, J/kgK)",
        "source": "IS 2185 Part 3:1984 / ECBC 2017",
        "reference": "Autoclaved Cellular Concrete Blocks",
        "valid_temperature_range": "-40°C to 100°C",
    },
    {
        "id": "dense-concrete",
        "name": "Reinforced Cement Concrete (RCC M25)",
        "category": "Structure",
        "description": "Structural cast-in-place dense concrete for floor slabs and shear elements.",
        "thermal_conductivity_k": 1.40,
        "density_rho": 2300.0,
        "specific_heat_cp": 880.0,
        "emissivity": 0.91,
        "solar_absorptivity": 0.72,
        "solar_reflectivity": 0.28,
        "embodied_carbon": 0.18,
        "cost": 2200.0,
        "units": "SI (W/mK, kg/m³, J/kgK)",
        "source": "IS 456:2000 / IS 3792",
        "reference": "Plain and Reinforced Concrete — Code of Practice",
        "valid_temperature_range": "-50°C to 120°C",
    },
    {
        "id": "cement-plaster",
        "name": "Cement Sand Plaster (1:4)",
        "category": "Finish",
        "description": "Interior and exterior protective rendering coat.",
        "thermal_conductivity_k": 0.72,
        "density_rho": 1600.0,
        "specific_heat_cp": 840.0,
        "emissivity": 0.91,
        "solar_absorptivity": 0.55,
        "solar_reflectivity": 0.45,
        "embodied_carbon": 0.19,
        "cost": 250.0,
        "units": "SI (W/mK, kg/m³, J/kgK)",
        "source": "IS 1661:1972",
        "reference": "Code of practice for application of cement and cement-lime plaster",
        "valid_temperature_range": "-40°C to 90°C",
    },
    {
        "id": "lime-plaster",
        "name": "Lime Surkhi Plaster",
        "category": "Finish",
        "description": "Traditional pozzolanic breathable hydraulic lime plaster.",
        "thermal_conductivity_k": 0.70,
        "density_rho": 1600.0,
        "specific_heat_cp": 840.0,
        "emissivity": 0.90,
        "solar_absorptivity": 0.52,
        "solar_reflectivity": 0.48,
        "embodied_carbon": 0.08,
        "cost": 280.0,
        "units": "SI (W/mK, kg/m³, J/kgK)",
        "source": "IS 2250:1981",
        "reference": "Code of practice for preparation and use of masonry mortars",
        "valid_temperature_range": "-30°C to 80°C",
    },
    {
        "id": "eps-insulation",
        "name": "Expanded Polystyrene (EPS)",
        "category": "Insulation",
        "description": "Closed-cell rigid thermal insulation foam board.",
        "thermal_conductivity_k": 0.035,
        "density_rho": 25.0,
        "specific_heat_cp": 1400.0,
        "emissivity": 0.90,
        "solar_absorptivity": 0.30,
        "solar_reflectivity": 0.70,
        "embodied_carbon": 3.29,
        "cost": 650.0,
        "units": "SI (W/mK, kg/m³, J/kgK)",
        "source": "IS 4671:1984 / ECBC 2017",
        "reference": "Expanded Polystyrene for Thermal Insulation",
        "valid_temperature_range": "-50°C to 75°C",
    },
    {
        "id": "xps-insulation",
        "name": "Extruded Polystyrene (XPS)",
        "category": "Insulation",
        "description": "High-compressive-strength, moisture-resistant rigid foam for roofs and perimeters.",
        "thermal_conductivity_k": 0.034,
        "density_rho": 35.0,
        "specific_heat_cp": 1400.0,
        "emissivity": 0.90,
        "solar_absorptivity": 0.30,
        "solar_reflectivity": 0.70,
        "embodied_carbon": 3.48,
        "cost": 850.0,
        "units": "SI (W/mK, kg/m³, J/kgK)",
        "source": "ASTM C578 / IS 12436",
        "reference": "Standard Specification for Rigid, Cellular Polystyrene Thermal Insulation",
        "valid_temperature_range": "-60°C to 75°C",
    },
    {
        "id": "rockwool",
        "name": "Mineral Rockwool Slab",
        "category": "Insulation",
        "description": "Non-combustible basalt stone wool insulation slab with high fire barrier rating.",
        "thermal_conductivity_k": 0.038,
        "density_rho": 80.0,
        "specific_heat_cp": 1030.0,
        "emissivity": 0.90,
        "solar_absorptivity": 0.40,
        "solar_reflectivity": 0.60,
        "embodied_carbon": 1.28,
        "cost": 750.0,
        "units": "SI (W/mK, kg/m³, J/kgK)",
        "source": "IS 8183:1993",
        "reference": "Bonded Mineral Wool for Thermal Insulation",
        "valid_temperature_range": "-50°C to 650°C",
    },
    {
        "id": "glass-wool",
        "name": "Glass Wool Batts",
        "category": "Insulation",
        "description": "Resin-bonded glass fiber batts for ceiling cavity and dry-wall acoustic/thermal fill.",
        "thermal_conductivity_k": 0.040,
        "density_rho": 24.0,
        "specific_heat_cp": 960.0,
        "emissivity": 0.90,
        "solar_absorptivity": 0.35,
        "solar_reflectivity": 0.65,
        "embodied_carbon": 1.35,
        "cost": 550.0,
        "units": "SI (W/mK, kg/m³, J/kgK)",
        "source": "IS 8183 / ASTM C553",
        "reference": "Mineral Fibre Thermal Insulation Material",
        "valid_temperature_range": "-40°C to 230°C",
    },
    {
        "id": "puf-board",
        "name": "Polyurethane / Polyisocyanurate Foam (PIR/PUR)",
        "category": "Insulation",
        "description": "Ultra-low thermal conductivity closed-cell insulation for extreme cold frontiers.",
        "thermal_conductivity_k": 0.024,
        "density_rho": 40.0,
        "specific_heat_cp": 1400.0,
        "emissivity": 0.90,
        "solar_absorptivity": 0.30,
        "solar_reflectivity": 0.70,
        "embodied_carbon": 4.10,
        "cost": 1100.0,
        "units": "SI (W/mK, kg/m³, J/kgK)",
        "source": "IS 12436:1988",
        "reference": "Preformed Rigid Polyurethane (PUR) and Polyisocyanurate (PIR) Foams",
        "valid_temperature_range": "-60°C to 110°C",
    },
    {
        "id": "mud-phuska",
        "name": "Mud Phuska (Traditional Roof Insulation)",
        "category": "Insulation",
        "description": "Clay puddle mixed with bhusa and cow dung; traditional composite insulation for Indian flat roofs.",
        "thermal_conductivity_k": 0.52,
        "density_rho": 1622.0,
        "specific_heat_cp": 880.0,
        "emissivity": 0.92,
        "solar_absorptivity": 0.65,
        "solar_reflectivity": 0.35,
        "embodied_carbon": 0.03,
        "cost": 350.0,
        "units": "SI (W/mK, kg/m³, J/kgK)",
        "source": "IS 2115:1980 / CPWD",
        "reference": "Code of practice for flat roof finish: Mud phuska",
        "valid_temperature_range": "-20°C to 80°C",
    },
    {
        "id": "cgi-sheet",
        "name": "Corrugated Galvanized Iron (CGI)",
        "category": "Roofing",
        "description": "Zinc-coated profiled mild steel cladding sheet.",
        "thermal_conductivity_k": 50.0,
        "density_rho": 7850.0,
        "specific_heat_cp": 500.0,
        "emissivity": 0.28,
        "solar_absorptivity": 0.65,
        "solar_reflectivity": 0.35,
        "embodied_carbon": 2.80,
        "cost": 680.0,
        "units": "SI (W/mK, kg/m³, J/kgK)",
        "source": "IS 277:2018",
        "reference": "Galvanized Steel Sheets (Plain and Corrugated) — Specification",
        "valid_temperature_range": "-50°C to 200°C",
    },
    {
        "id": "aluminum-sheet",
        "name": "Corrugated Aluminum Roofing Sheet",
        "category": "Roofing",
        "description": "High-reflectivity lightweight alloy sheet with low longwave emissivity.",
        "thermal_conductivity_k": 205.0,
        "density_rho": 2700.0,
        "specific_heat_cp": 900.0,
        "emissivity": 0.09,
        "solar_absorptivity": 0.40,
        "solar_reflectivity": 0.60,
        "embodied_carbon": 8.24,
        "cost": 1250.0,
        "units": "SI (W/mK, kg/m³, J/kgK)",
        "source": "IS 737:2008 / IS 1254",
        "reference": "Wrought Aluminium and Aluminium Alloy Sheet and Strip",
        "valid_temperature_range": "-60°C to 250°C",
    },
    {
        "id": "timber-plywood",
        "name": "Commercial Plywood / Timber",
        "category": "Wood",
        "description": "Boiling water resistant structural plywood / coniferous timber panelling.",
        "thermal_conductivity_k": 0.13,
        "density_rho": 550.0,
        "specific_heat_cp": 1700.0,
        "emissivity": 0.90,
        "solar_absorptivity": 0.60,
        "solar_reflectivity": 0.40,
        "embodied_carbon": 0.45,
        "cost": 850.0,
        "units": "SI (W/mK, kg/m³, J/kgK)",
        "source": "IS 303:1989 / IS 710",
        "reference": "Plywood for General Purposes — Specification",
        "valid_temperature_range": "-40°C to 80°C",
    },
    {
        "id": "glazing-double-low-e",
        "name": "Double Glazing Low-E (4-12-4 Air)",
        "category": "Glazing",
        "description": "Insulated double glazing unit with soft-coat Low-E on surface #3. Equivalent U=1.8 W/m²K, SHGC=0.45.",
        "thermal_conductivity_k": 0.040,  # Effective equivalent thermal conductivity across unit
        "density_rho": 2500.0,
        "specific_heat_cp": 840.0,
        "emissivity": 0.15,
        "solar_absorptivity": 0.25,
        "solar_reflectivity": 0.45,
        "embodied_carbon": 1.45,
        "cost": 3200.0,
        "units": "SI (W/mK, kg/m³, J/kgK)",
        "source": "IS 2553 / NFRC 100 / ECBC 2017",
        "reference": "Safety Glass / ECBC Prescriptive Fenestration Compliance",
        "valid_temperature_range": "-40°C to 80°C",
    },
]

from datetime import datetime

# Helper to build the preset structure for MongoDB
PRESET_PROJECTS = []
presets = [
    {
        "id": "leh-winter-demo",
        "name": "Leh High-Altitude Winter Outpost",
        "description": "Critical cold defense shelter at 3,500m elevation. Extreme diurnal swings with sub-zero design extremes (-15°C) and high solar clear-sky insolation.",
        "loc_name": "Leh, Ladakh",
        "lat": 34.15,
        "lon": 77.58,
        "elev": 3500.0,
        "zone": "Cold and Sunny (High Altitude)",
    },
    {
        "id": "jaisalmer-hot-arid",
        "name": "Thar Desert Arid Deployment",
        "description": "High thermal mass construction designed to delay diurnal solar flux penetration in hot-dry desert climates with 45°C ambient peaks.",
        "loc_name": "Jaisalmer, Rajasthan",
        "lat": 26.91,
        "lon": 70.90,
        "elev": 225.0,
        "zone": "Hot and Dry",
    },
    {
        "id": "tawang-subalpine",
        "name": "Tawang Mountain High-Humidity Post",
        "description": "Damp cold high-elevation outpost with freezing rain, mist, and persistent overcast skies. High airtightness and continuous moisture barrier required.",
        "loc_name": "Tawang, Arunachal Pradesh",
        "lat": 27.58,
        "lon": 91.86,
        "elev": 3048.0,
        "zone": "Cold and Cloudy",
    }
]

for p_data in presets:
    now = datetime.utcnow()
    proj = {
        "_id": p_data["id"],
        "id": p_data["id"],
        "name": p_data["name"],
        "description": p_data["description"],
        "created_at": now
    }
    loc = {
        "_id": f"loc-{p_data['id']}",
        "id": f"loc-{p_data['id']}",
        "project_id": p_data["id"],
        "name": p_data["loc_name"],
        "latitude": p_data["lat"],
        "longitude": p_data["lon"],
        "elevation": p_data["elev"],
        "elevation_source": "provider",
        "climate_zone": p_data["zone"],
        "created_at": now
    }
    canonical = {
        "id": p_data["id"],
        "name": p_data["name"],
        "location": {
            "name": p_data["loc_name"],
            "latitude": p_data["lat"],
            "longitude": p_data["lon"],
            "elevation": p_data["elev"],
            "climate_zone": p_data["zone"],
        }
    }
    scenario = {
        "_id": f"scenario-{p_data['id']}",
        "id": f"scenario-{p_data['id']}",
        "project_id": p_data["id"],
        "name": p_data["name"],
        "version": 1,
        "location_id": loc["id"],
        "canonical_json": json.dumps(canonical),
        "created_at": now
    }
    PRESET_PROJECTS.append({
        "project": proj,
        "location": loc,
        "scenario": scenario
    })
